version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      github-actions:
        patterns:
          - '*'
    labels:
      - 'dependencies'
      - 'ci'
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      npm-production:
        dependency-type: 'production'
      npm-development:
        dependency-type: 'development'
        update-types:
          - 'minor'
          - 'patch'
    labels:
      - 'dependencies'
  - package-ecosystem: 'cargo'
    directory: '/occt/codegen'
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
